name: waya
description: "Walk assist with your AI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0
  audioplayers: ^5.2.1
  geolocator: ^10.1.0
  camera: ^0.10.5
  flutter_tts: ^3.8.4
  http: any
  path_provider: ^2.1.1
  path: ^1.9.0
  easy_localization: ^3.0.7+1
  image: ^4.1.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/langs/
    - assets/sound/
