name: waya
description: "Walk Assist With Your AI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.0
  url_launcher: ^6.1.5
  permission_handler: ^11.3.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.6.3
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/langs/
    - assets/sound/
